### ISSUE TITLE
Not working/Detecting the card when using the WOL version

### ISSUE THREAD

**Issue by acermez** [maaeps/IntelMausiEthernet-WOL#1]
Hey There,
Thank you for posting the patched/updated Kext file, I tried it but I can't seem to get it to work. I mean when using the original intelMausi.kext file, the Ethernet network is working, but when using the WOL version, it doesn't recognize the ethernet card anymore. So just to confirm, should I rename the Kext file from "-WOL" to just IntelMausiEthernet.kext? and also, where are you pasting it, Clover/other folder or L/E? I tried both, no luck with the WOL version, working great with Mieze's original version.
Thank you!

**Comment by acermez** [comment]
Ok, I have been googling about this issue for a couple of weeks before I posted it here, but just now, I was able to find the attached Kext file that made my ethernet card available and WOL active as well (finally). I hope it could help someone and I'm still not sure why this repo Kext did not work. If anyone finds out, please let me know, thanks again!
Direct link to the original author Kext file: https://www.hackintosh-forum.de/forum/user-post-list/58758-anonymcoder/?pageNo=4

[IntelMausi-WOL.kext.zip](https://github.com/maaeps/IntelMausiEthernet-WOL/files/4704879/IntelMausi-WOL.kext.zip)

PS: My motherboard is GA-z97x-ud3h and using Mojave 10.14.6 with Clover r5118 while using the Kext from EFI/Clover/Kexts/other

**Comment by fischerscode** [comment]
Just to clarify:
You tried the kext from [here](https://github.com/maaeps/IntelMausiEthernet-WOL/releases/tag/v2.5.1d1) and it did not work.
Then you tried the kext from [here](https://www.hackintosh-forum.de/forum/thread/46188-kext-f%C3%BCr-wol-nach-shutdown/?postID=563628#post563628) and it worked. (The IntelMausiEthernet-WOL.kext) (Should be the same one as [this](https://github.com/maaeps/IntelMausiEthernet-WOL/releases/tag/v1.1))

**Comment by acermez** [comment]
Correct,

IntelMausi-WOL.kext (Worked) 
IntelMausiEthernet-WOL.kext (Did not work)

I'm not sure if it's the name difference but when I inspected the package content (right-click on kext file > show package content), it seems that IntelMausi-WOL.kext is correctly named in the Info.plist file, unlike the "IntelMausiEthernet-WOL.kext" which has an extra folder "_CodeSignature" and the Info.plist file is still using "IntelMausiEthernet" without the "-WOL". I'm not a kext expert (I'm actually a backend Web Developer) so I'm not sure if that's the case here or it is just the fact that both kexts are not from the same repo (I see you forked each one to enable WOL separately):

https://github.com/maaeps/IntelMausiEthernet-WOL
https://github.com/maaeps/IntelMausi-WOL

Thank you for your reply!

**Comment by fischerscode** [comment]
I am not an kext/macos expert, too.
But as far as I know is IntelmausiEthernet the original kext. IntelMausi is a fork and supports some more chips. (Not sure about this)

As you have already noticed, I have indeed forked both versions.
Thanks for the issue, I will leave a link in the README.

**Comment by fischerscode** [comment]
I finaly did so...
I am closing this issue now. Feel free to reopen it.
Thanks again!
