### ISSUE TITLE
stuck as apple logo when I change  IntelMausi to IntelMausiEthernet-WOL

### ISSUE THREAD

**Issue by michael-kj** [maaeps/IntelMausiEthernet-WOL#2]
sorry,I dont know how to debug.  please tell if need other info  
btw,I use oc.

**Comment by fischerscode** [comment]
Have you tried using [IntelMausi-WOL](https://github.com/fischerscode/IntelMausi-WOL)?
As it is a fork of IntelMausi it should work better for you.

**Comment by michael-kj** [comment]
> Have you tried using [IntelMausi-WOL](https://github.com/fischerscode/IntelMausi-WOL)?
> As it is a fork of IntelMausi it should work better for you.

tks for reply.
well,good news: I can login the system.
bad news: still can't wol.  I will dig harder .
